server:
  port: 44008
spring:
  application:
    name: SpringBoot_RabbitMq_Producer
    rabbitmq:
      host: 192.168.241.128
      port: 5672
      username: admin
      password: 123456
      virtualHost: /
