server:
  port: 44000
spring:
  application:
    name: SpringBoot_RabbitMq_Consumer
    rabbitmq:
      host: 192.168.1.50
      port: 5672
      username: admin
      password: 123456
      virtualHost: /
